

spring:
  application:
    name: Employee

  datasource:
    url: jdbc:mysql://localhost:3306/empdb?useSSL=false
    username: root
    password: maa@1977
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect